@apiurl={{$dotenv API_URL}}
@token={{$dotenv TEMP_TOKEN}}
###
POST {{apiurl}}/users
Content-Type: application/json

{
    "username": "aaaa",
    "password": "123456"
}

###
POST {{apiurl}}/users/login
Content-Type: application/json

{
    "username": "Test",
    "password": "1234"
}

###
PUT {{apiurl}}/users
Content-Type: application/json
Authorization:  Bearer {{token}}

{
    "newRating": "1500"
}

###
DELETE {{apiurl}}/users
Content-Type: application/json
Authorization:  Bearer {{token}}

###
POST {{apiurl}}/games
Content-Type: application/json
Authorization:  Bearer {{token}}

{
    "player1Id": "6706cbe62c4b288d7679e4fb",
    "player2Id": "6707eaf9b75c8fb263391580",
    "moves": ""
}